### ISSUE TITLE
Question about dataset sampling

### ISSUE THREAD

**Issue by issakh** [danielism97/ST-MFNet#5]
Hi, I came across your work and thought it was a very interesting concept. I see you randomly sample from the vimeo90k and bvi sets. When you were doing your ablations, how did you manage to get the list of randomly sampled frames and load them for each experiment?
The reason I'm asking is I am currently looking at different training parameters to see if there's a quicker way for the model to converge (as currently takes about 16 days on one GPU if I use the full vimeo90k for reference), but if the dataset is sampled at each random the comparison would not necessarily account for the variance in training data.
Thanks

**Comment by danier97** [comment]
Hi, thank you for your interest in our work and your question!

The training data from BVI-DVC dataset are generated before training, i.e. the 256x256 quintuplets are randomly sampled beforehand, instead of during the training. You can find those quintuplets [here](https://uob-my.sharepoint.com/:f:/g/personal/mt20523_bristol_ac_uk/EnHgdYU1cwNEhl-3BXFL8ncBXXGpg7u3N_oiXQ4OJuLXtw?e=fxdITc). 

For Vimeo90K-septuplet dataset, there is no need to sample frames because they already come as septuplets. We make use of all septuplets to create quintuplets for training, i.e. we use frames 1, 3, 5, 7 as input and frame 4 as the GT label. However, for Vimeo90K we do perform random cropping of 256x256 quintuplets from the 448x256 quintuplets during training, and this is a common approach in the literature. I agree that there might be some noise introduced here because of this random cropping, but I highly doubt this would be significant enough to affect the conclusions, because 256x256 patches sampled from 448x256 images are likely to be quite similar.

Regarding the slow convergence and inference, we experienced the same issue, and it is indeed a shortcoming of our method - apologies for the inconvenience! I am currently working on reducing the complexity of the model, and will update on this as soon as I get any good resutls.

Many thanks.

**Comment by issakh** [comment]
Thanks for your quick response, I really appreciate it. 
My main question is the Sampler in line 62 of your train code. I just realised, when looking at the code iter=True, so the entire BVI and vimeo sets would be used for training? The only time you'd want to choose samples=1000 is for debugging right?

Also, for tests with SNU film, which one should I download. Is it the triplet or all RGB frames? And would I have to sort them or would the testsets.py do that for me?

Thanks again

**Comment by danier97** [comment]
> My main question is the Sampler in line 62 of your train code. I just realised, when looking at the code iter=True, so the entire BVI and vimeo sets would be used for training? The only time you'd want to choose samples=1000 is for debugging right?

Yes, that is correct.

> Also, for tests with SNU film, which one should I download. Is it the triplet or all RGB frames? And would I have to sort them 
or would the testsets.py do that for me?

You need all the RGB frames, and the four `.txt` files SNUFILM uses to specify the test triplets. To avoid having to modify the code, after you download all frames and thet text files you can arrange the directories as specified in README. 

I hope this helps.
